sonar.projectKey=JuanJoseArenas_CatalogoParametros-FrontEnd
sonar.organization=juanjosearenas
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,src/environments/**
sonar.coverage.exclusions=src/main.ts,src/app/app.config.ts,src/app/**/*.routes.ts,src/environments/**
sonar.javascript.lcov.reportPaths=coverage/catalogo-parametros-front/lcov.info
sonar.sourceEncoding=UTF-8
